# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
# 現状だと、kubeadm.k8s.io/v1beta3が最新のAPIバージョン
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: kinsho-cluster
networking:
  # Flannelによって↓この範囲でPod間通信が行われる
  podSubnet: 10.244.0.0/16
  # Serviceを作成し割り当てられるIPアドレスの範囲
  serviceSubnet: 10.97.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.10.2
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.10.2
  criSocket: /var/run/crio/crio.sock
